### ISSUE TITLE
Save Loadout

### ISSUE THREAD

**Issue by dracuslayer** [TGRHavoc/fivem-loadouts#10]
Its not really a problem its more a request i used this https://forum.fivem.net/t/release-simple-ped-models-clothes-and-props-editor-v1-0-updated-09-january2017/2674 to edit my loadout and then save it to the datebase. but when spawning my loadout back in it disabled what i changed. it set the loadout to default. i like the ability to edit my loadout with that tool. only issue is its binded to my controller. also having to redue it everytime i load up is not good. i would like to see the ability to edit the loadout characters and save them and they will load in as it was saved. if this is possible. thanks.

**Comment by TGRHavoc** [comment]
I am not the developer for the plugin you've provided. Therefore, I am not going to change it to include saving it's changes to the database. If you want this feature, ask the developer (MarkViolla) nicely if they will add it.
