### ISSUE TITLE
I want something else than "permission_level"

### ISSUE THREAD

**Issue by Cr4zZyBipBiip** [TGRHavoc/fivem-loadouts#3]
Hi, for my server, I will user "jobid" in my DB...
Like jobid=5 == Police
jobid=6 == EMS

I want to "block" other people to get this skin, I already changed the >= loadout.permission_level // to ==

BUT
I changed ALL the "permission_level" to "jobid" in all of your .lua... thinking it will work..but no...

Maybe the user.jobid isn't reach...? can you help me pls ?

**Comment by TGRHavoc** [comment]
Do you _need_ to rename the property?

You can probably get the behaviour you want just by changing lines 57 and 76 of server.lua to

```
if user.permission_level == (loadout.permission_level or 0) then
```
Then  "permission_level" acts as a "jobid".

Edit: How is the "jobid" being set onto the player? Are you doing it via essentialmode or, is it a custom script?.

You would have to  check the "permission_level" of the loadout against this value (if it's not being stored in the user's "permission_level" from essentialmode).

**Comment by Cr4zZyBipBiip** [comment]
permission_level is used for admin command...I want the loadout script to use "jobid" column instead of permission_level

**Comment by TGRHavoc** [comment]
> to use "jobid" column instead

EssentialMode doesn't have a "jobid" column. You would have to add this feature yourself.

**Comment by Cr4zZyBipBiip** [comment]
I've my jobid column, but : 
`TriggerEvent("es:addCommand", "loadout", function(source, args, user)
    if #args > 1 then
        local arg = args[2]

        if LOADOUTS[arg] then
            -- Do loadout
            local loadout = LOADOUTS[arg]

            print("checking permission levels")
            local player = user.identifier
            local nbjobid = MySQL:executeQuery("SELECT jobid FROM users WHERE identifier = '@username'",{['@username'] = player})
            local result = MySQL:getResults(nbjobid, {'jobid'})
      
            print(tonumber(result))
            if tonumber(result[1].jobid) == loadout.jobid then
                print("executing command..." .. tostring(loadout.skins) .. " " .. tostring(loadout.weapons))

                TriggerEvent("loadout:doLoadout", source, arg)
                TriggerClientEvent("loadout:missiontext", source, "You have been given the loadout " .. loadout.name, 5000)

                return
            end

            -- They don't have permission
            print("no permission")
            TriggerClientEvent("loadout:missiontext", source, "You do not have permission for the " .. loadout.name .. " loadout", 5000)

        else
            -- TODO: Other commands? e.g. /loadout help
            if arg == "help" then
                local availableCommands = {}
                for command in pairs(commands) do
                    local permission = LOADOUTS[commands[command]].jobid
                    if tonumber(result[1].jobid) >= (permission or 0) then
                        table.insert(availableCommands, commands[command])
                    end
                end

                TriggerClientEvent('chatMessage', source, "Loadouts", {255, 255, 255}, "There are " .. #availableCommands .. " loadouts to choose from.")
                TriggerClientEvent("chatMessage", source, "Loadouts", {255, 255, 255}, table.concat(availableCommands, ", "))
            end
        end
    else
        TriggerClientEvent('chatMessage', source, "Loadouts", {255, 255, 255}, "Use /loadout <id> to pick a loadout.")
        TriggerClientEvent("chatMessage", source, "Loadouts", {255, 255, 255}, "Use /loadout help to get a list of available loadouts.")
    end
end)`

but I missed something I think...
