### ISSUE TITLE
More Randomization

### ISSUE THREAD

**Issue by AlphaKing112** [TGRHavoc/fivem-loadouts#7]
After testing the loadouts I notice its limited with the randomization I just see the hair changes can there be more randomization such as the shirts legs, props like gun holster or bank bag. As well add in randomization like hats or glasses on ped.

**Comment by TGRHavoc** [comment]
> After testing the loadouts I notice its limited with the randomization I just see the hair changes can there be more randomization such as the shirts legs, props like gun holster or bank bag. As well add in randomization like hats or glasses on ped.

Yea, I've noticed that too with certain modes. I don't think it's a limitation of the addon but, a limitation within GTA itself. Just to double check though, can you check the F8 console?

It'll look something like this:

![console example](https://cloud.githubusercontent.com/assets/1770893/25307883/286281f6-27a1-11e7-9183-074a1e5182a5.png)

It'll show you what can be randomized and what the values are. It's in the format of "(selected/max)" where "selected" is the randomized number it's currently set to and "max" is the number of possible variants.

**Comment by AlphaKing112** [comment]
this is the swat onI just got pants randomized I check the cop now
![capture](https://cloud.githubusercontent.com/assets/17770052/25308278/a12ef3d0-277e-11e7-872a-40bb5d69ed21.PNG)

**Comment by AlphaKing112** [comment]
this is the cop one 
![capture](https://cloud.githubusercontent.com/assets/17770052/25308342/d92bd720-277f-11e7-90ff-0750d8deb992.PNG)

**Comment by TGRHavoc** [comment]
Yea, I thought so. There's not much that can be customized on either of those models 😢 
There's nothing I can do about this without it looking weird or crashing the client.

You could mitigate this by adding more police character (e.g. SWAT models and cop models) and hope for the best :/

Note: If you want to test the randomization on all characters regardless, you can remove the validity checks. Just know, it's not going to look great.

E.g.
```lua
if IsPedComponentVariationValid(GetPlayerPed(-1), id, randomNumber, 2) then
    SetPedComponentVariation(GetPlayerPed(-1), id, randomNumber, 1, 2)
end
```
to
```lua
SetPedComponentVariation(GetPlayerPed(-1), id, randomNumber, 1, 2)
```

Edit: I'm going to mark this as "invalid" as it doesn't really pertain to the addon.

**Comment by AlphaKing112** [comment]
where u change the code at?

**Comment by TGRHavoc** [comment]
Ah, sorry, forgot to add that 😛 

The client side script file "client.lua" from line 327 to like 340.

**Comment by AlphaKing112** [comment]
like this lol?
![capture](https://cloud.githubusercontent.com/assets/17770052/25308756/df01d8b6-2789-11e7-9f5d-1c3c97a83d26.PNG)

**Comment by TGRHavoc** [comment]
Yeah, like that 😄
